spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: ec2-3-231-110-127.compute-1.amazonaws.com:9096,ec2-3-227-129-191.compute-1.amazonaws.com:9096,ec2-100-24-239-47.compute-1.amazonaws.com:9096,ec2-35-168-34-44.compute-1.amazonaws.com:9096,ec2-3-208-232-40.compute-1.amazonaws.com:9096,ec2-3-234-75-100.compute-1.amazonaws.com:9096,ec2-3-220-121-33.compute-1.amazonaws.com:9096,ec2-100-25-107-37.compute-1.amazonaws.com:9096
    ssl:
      trust-store-location: classpath:/client-certs/truststore.jks
      trust-store-password: password123
      key-store-location:  classpath:/client-certs/keystore.jks
      key-store-password: password123
    consumer:
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
